### ISSUE TITLE
Consider caching downloads at build time, rather than at runtime

### ISSUE THREAD

**Issue by rdeits** [tkoolen/ValkyrieRobot.jl#1]
I'm switching the RBTInspector demo to use ValkryieRobot.jl rather than hard-coding a path to Drake, but I noticed that I have to actually construct a Valkyrie() object in order to ensure that the URDFs get cached. Could we do that at Pkg.build() time instead so that things like RBTInspector can get the URDF right away?

**Comment by tkoolen** [comment]
Yes, that sounds like the right thing to do.

**Comment by tkoolen** [comment]
I'll try to get that to work sometime this week.
